#! /bin/bash 								       							       
# Mustafa Ahmed 							       							       							      
# 									       
# bubble_sort                                                                  
# 2021-04-05                                                                   
# This script sorts an array of nubers from least to greatest from a user input

echo "Enter between 4 and 12 characters in any order";

read -a array;
length=${array[@]}; #cant seem to get for loop to work with array length stored as a variable 

while [ ${#array[@]} -lt 4 ] || [ ${#array[@]} -gt 12 ] #ensure user enters data between 4 and 12 total numbers
do	
	echo "Please enter a minimum of 4 or max 12";
	read -a array;
done;

for ((i=0; i<${#array[@]}; i++)) #0 indice and upwards
do
	for ((j=0; j<(${#array[@]}-i-1); j++)) #next indice until upper indice less 1
	do
		if [ ${array[j]}  -gt  ${array[j+1]} ] #evaluate which is larger
		then
			swap=${array[j]}; #swap positions in the array and print before running loop again
			array[$j]=${array[$((j+1))]};
			array[$((j+1))]=$swap;
			echo ${array[*]};
		fi
	done
done
echo ${array[*]};
